## Baseline Model

In [20]:
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

### Sélection de variables

In [21]:
train_data = pd.read_csv("../data/processed_dataset.csv")
test_data = pd.read_parquet("../data/test_data.parquet")

test_data.head()

,ID_Employe,Age,Sexe,Departement,Annees_Experience,Niveau_Etudes,Salaire_Mensuel_BIF,Travail_A_Distance,Heures_Supplementaires,Heures_Formation,...,Departement_Administration,Departement_Commercial,Departement_Finance,Departement_Informatique,Departement_Logistique,Departement_Marketing,Departement_Production,Departement_Recherche et Développement,Departement_Ressources Humaines,Departement_Support Client
0,433,0.203711,0.0,Marketing,-0.311942,1.0,-0.187169,0.0,-1.289932,0.655394,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,398,-1.590189,0.0,Marketing,-0.900686,1.0,-0.920043,0.0,-0.672980,0.860110,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,432,-0.479679,0.0,Finance,-0.782937,0.0,-0.840417,0.0,-0.056028,1.211052,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,371,0.024057,0.0,Production,2.160784,1.0,0.652730,0.0,-1.289932,-0.221961,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,407,-1.419341,0.0,Informatique,-0.900686,1.0,-0.784460,0.0,0.120245,-1.070071,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
X_train = train_data.drop(["ID_Employe", "Satisfait"],axis=1).select_dtypes(include=["number"])
y_train = train_data["Satisfait"]

### Transformation de données de test

In [23]:
# Les variables numériques
# feature_cols = ["AgeMaison", "Quartier_Target", "Indicateur_Confort", "Chambres_par_Superficie", "LoyerMensuel_Log1"]

# for col in ['Salon', 'SalleDeBainInterieure', 'Parking', 'Meuble', 'Jardin']:
#     test_data[col + "_Bin"] = test_data[col].map({"Oui": 1, "Non": 0}).fillna(0).astype(int)

# neighbourhood_encoder = joblib.load("neighbourhood_encoder.joblib") 
# test_data["Quartier_Target"] = neighbourhood_encoder.transform(test_data[["Quartier"]])[:, 0]

# test_data["LoyerMensuel_Log1"] = np.log1p(test_data["LoyerMensuel_BIF"])

# Création de variables utiles pour le test
# cols_confort = ['Salon_Bin', 'SalleDeBainInterieure_Bin', 'Parking_Bin', 'Meuble_Bin', 'Jardin_Bin']
# test_data['Indicateur_Confort'] = test_data[cols_confort].sum(axis=1)

# test_data['Chambres_par_Superficie'] = test_data['Chambres'] / (test_data['Superficie_m2'] + 0.1)

# Séparation de X_test et y_test
X_test = test_data.drop(
    ["ID_Employe", "Satisfait"],
    axis=1).select_dtypes(include=["number"])
y_test = test_data["Satisfait"]

X_test

,Age,Sexe,Annees_Experience,Niveau_Etudes,Salaire_Mensuel_BIF,Travail_A_Distance,Heures_Supplementaires,Heures_Formation,Anciennete_Entreprise,Nombre_Promotions,...,Departement_Administration,Departement_Commercial,Departement_Finance,Departement_Informatique,Departement_Logistique,Departement_Marketing,Departement_Production,Departement_Recherche et Développement,Departement_Ressources Humaines,Departement_Support Client
0,0.203711,0.0,-0.311942,1.0,-0.187169,0.0,-1.289932,0.655394,-0.599124,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,-1.590189,0.0,-0.900686,1.0,-0.920043,0.0,-0.672980,0.860110,-0.423750,2.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,-0.479679,0.0,-0.782937,0.0,-0.840417,0.0,-0.056028,1.211052,-0.774498,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.024057,0.0,2.160784,1.0,0.652730,0.0,-1.289932,-0.221961,-0.949873,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,-1.419341,0.0,-0.900686,1.0,-0.784460,0.0,0.120245,-1.070071,-0.599124,1.2,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,0.801677,1.0,2.514031,1.0,1.419495,0.0,0.913469,-0.104980,3.609862,6.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
124,0.545406,0.0,-0.547440,0.0,-0.917386,0.0,-1.642476,-0.280451,0.102374,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
125,1.485068,1.0,1.572040,1.0,1.988563,0.0,-1.113660,0.421432,2.031492,1.2,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
126,-0.906798,0.0,-0.311942,1.0,0.012349,0.0,0.913469,-1.596484,0.277748,3.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
127,0.024057,1.0,-1.018435,0.0,-1.269052,1.0,1.001605,-1.450258,-0.599124,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

### Dummy Régression

In [28]:
dummy_model = DummyClassifier(strategy="most_frequent").fit(X_train, y_train)

y_predict_dummy = dummy_model.predict(y_test)

print(f"y_predict_dummy_mean : {y_predict}")

y_predict_dummy_mean : [0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0.
 0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0.
 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1.
 0. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1.
 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0.
 1. 1. 1. 1. 0. 1. 0. 0.]

### Régression Linéaire simple

In [26]:
model = LogisticRegression(max_iter=1000).fit(X_train, y_train)
y_predict = model.predict(X_test)

y_predict_series = pd.Series(y_predict, index=y_test.index)

compareson = pd.DataFrame({
    "Réel": y_test,
    "Prédict": y_predict_series
})

print(compareson.head(5))

   Réel  Prédict
0   0.0      0.0
1   1.0      1.0
2   0.0      1.0
3   1.0      0.0
4   1.0      0.0

### Analyse des erreurs

In [29]:
print(f"dummy accuracy : {accuracy_score(y_test, y_predict_dummy)}")
print(f"dummy precision : {recall_score(y_test, y_predict_dummy)}")
print(f"dummy recall : {recall_score(y_test, y_predict_dummy)}")
print(f"dummy f1 score : {f1_score(y_test, y_predict_dummy)}")
print()
print(f"Linear accuracy : {accuracy_score(y_test, y_predict)}")
print(f"Linear precision : {recall_score(y_test, y_predict)}")
print(f"Linear recall : {recall_score(y_test, y_predict)}")
print(f"Linear f1 score : {f1_score(y_test, y_predict)}")

dummy accuracy : 0.6171875
dummy precision : 1.0
dummy recall : 1.0
dummy f1 score : 0.7632850241545893

Linear accuracy : 0.8359375
Linear precision : 0.8607594936708861
Linear recall : 0.8607594936708861
Linear f1 score : 0.8662420382165605